### ISSUE TITLE
vertx-dependencies has multiple non resolvable artifacts

### ISSUE THREAD

**Issue by paulgallagher75** [vert-x3/vertx-dependencies#14]
vertx-dependencies dependencyManagement section has references to multiple vertx artifacts that do not exist -

io.vertx:vertx-consul
io.vertx:vertx-mongo
io.vertx:vertx-mail
io.vertx:vertx-jgroups (last released 3.5.0.Beta1)
io.vertx:vertx-maven-service-factory-parent (last released 3.1.0)

I checked on maven central and they were last released for version 3.5.1 (unless stated along side the artifact) and are still in the 3.5.3 branch and master (3.6) so I guess they were never removed when the projects changed.

**Comment by vietj** [comment]
indeed, it's not a problem per se because it's dependency management, but it deserves a cleanup
