### ISSUE TITLE
Vert.x 4.4.5 jackson-core dependency

### ISSUE THREAD

**Issue by tageldart** [vert-x3/vertx-dependencies#154]
Vert.x 4.4.5 appears to have a dependency on jackson-core 2.15.0, which introduced a breaking change in the default max String value length (https://github.com/FasterXML/jackson-core/issues/1014).

Would you please consider updating the jackson-core dependency in a future  release?

**Comment by tsegismont** [comment]
Sounds good to me

**Comment by tsegismont** [comment]
Fixed by #155
