### ISSUE TITLE
update jackson in 3.9.0 to latest patch version

### ISSUE THREAD

**Issue by encodeering** [vert-x3/vertx-dependencies#40]
#### Describe the feature

It seems that jackson is updated to the 2.10.x line in the upcoming version 3.9.0 and they have released another patch version. It might be valuable to update to 2.10.3 before releasing 3.9.0

#### Use cases

https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10.3

**Comment by pmlopes** [comment]
3.9.0 is released with jackson 2.10.2
