### ISSUE TITLE
Update to latest netty netty 4.1.49.Final

### ISSUE THREAD

**Issue by zenios** [vert-x3/vertx-dependencies#44]

**Comment by vietj** [comment]
there is a CQ open for that, that is waiting to be resolved

**Comment by zenios** [comment]
@Viet Sorry for my ignorance but what exactly is CQ? :)

**Comment by vietj** [comment]
ah sorry :-), it means Contribution Questionnaire and it assess the dependency can be used in eclipse-vertx : here is the CQ for Netty 4.1.49.Final https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21983

**Comment by zenios** [comment]
ah ok.Thanks a lot
